// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvKaqAh2W0KVlvz_eYu0MqqCOyj0dHJXM',
    appId: '1:1068062627965:web:82195ba02d17cf6b9c3914',
    messagingSenderId: '1068062627965',
    projectId: 'eurosom-5bd44',
    authDomain: 'eurosom-5bd44.firebaseapp.com',
    databaseURL:
    'https://flutterfire-e2e-tests-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'eurosom-5bd44.appspot.com',
    measurementId: 'G-JN95N1JV2E',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB5krclnShYGOe0YBqjWvPPbUL3UnzWTo',
    appId: '1:232305822061:android:7cd190c55d46b6119ef264',
    messagingSenderId: '232305822061',
    projectId: 'os-muslim-assistant',
    storageBucket: 'os-muslim-assistant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSecWdPHI5pfrB2bVIVLHUrTuwca7zyGQ',
    appId: '1:232305822061:ios:5f56c5784d2b40209ef264',
    messagingSenderId: '232305822061',
    projectId: 'os-muslim-assistant',
    storageBucket: 'os-muslim-assistant.appspot.com',
    iosClientId: '232305822061-em5orrtvnn1cuf3ve181aqu6ae0rceo5.apps.googleusercontent.com',
    iosBundleId: 'com.ninetyplus.muslim',
  );
}
